name: Demo
run-name: ${{ github.actor }}
on: [push]

jobs:
  syft:
    runs-on: ubuntu-latest
    
    steps:
    - name: scan with syft
      uses: anchore/sbom-action@v0.15.10
      with:
        image: cobbgcloud/timeoff:29
      id: myid
