name: CONTAINER_IMAGE_CI
run-name: ${{ github.actor }}
on: 
  workflow_dispatch

jobs:
  app_container:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Build and push container image to local
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: localhost:5000/cobbgcloud/timeoff:latest
        
    - name: Scan with Grype
      uses: anchore/scan-action@v3.6.4
      id: scan
      with:
        image: localhost:5000/cobbgcloud/timeoff:latest
        fail-build: false
    
    - name: Upload Sarif report.
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    - name: 
