name: Demo
run-name: ${{ github.actor }}
on: [push]

jobs:
  grype:
    runs-on: ubuntu-latest
    
    steps:
    - name: scan with grype
      uses: anchore/scan-action@v3.6.4
      with:
        image: cobbgcloud/timeoff:29
        fail-build: false
        severity-cutoff: critical
    - name: Upload to GitHub Security Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
