name: Demo
run-name: ${{ github.actor }}
on: [push]

jobs:
  syft:
    runs-on: ubuntu-latest
    
    steps:
    - name: scan with grype
      uses: anchore/scan-action@v3.6.4
      with:
        image: cobbgcloud/timeoff:29
        fail-build: true
        severity-cutoff: critical
