name: Demo
run-name: ${{ github.actor }}
on: [push]

jobs:
  syft:
    runs-on: ubuntu-latest
    
    steps:
    - name: scan with syft
      uses: anchore/sbom-action@v0.15.10
      with:
        image: cobbgcloud/timeoff:29

    - name: publishing SBOMs
      uses: anchore/sbom-action/publish-sbom@v4
      with:
        sbom-artifact-match: ".*\\.spdx$"
